export const questionImages: Record<string, string> = {
  q1: require("./questions/q1.png"),
  q2: require("./questions/q2.png"),
  q3: require("./questions/q3.png"),
  q4: require("./questions/q4.png"),
  q5: require("./questions/q5.png"),
  q6: require("./questions/q6.png"),
  q7: require("./questions/q7.png"),
  q8: require("./questions/q8.png"),
  q9: require("./questions/q9.png"),
  q10: require("./questions/q10.png"),
  q11: require("./questions/q11.png"),
  q12: require("./questions/q12.png"),
  q13: require("./questions/q13.png"),
};
